import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/header";
import { ReactLenis } from "lenis/react";

import { Montserrat } from "next/font/google";

const sinisuka = localFont({
  src: "./fonts/sinisuka-webfont.woff",
  variable: "--font-sinisuka",
  weight: "100 900",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sinisuka.variable} ${montserrat.className} antialiased`}
      >
        <Header />
        <ReactLenis root>{children}</ReactLenis>
      </body>
    </html>
  );
}
